### ISSUE TITLE
A new release would be needed so that the action is usable again

### ISSUE THREAD

**Issue by dil-atoth** [roryprimrose/rungitversion#9]
Hey!

So the 1.0.0 release was created a long time ago, and when I'm trying to use the action, since it uses the old image in the Dockerfile, it straight up fails.

Could you please create a new release with the latest code, so that the action can be used?

Thank you in advance.

**Comment by roryprimrose** [comment]
Hi there,

I created this GitHub action because at the time there was no GitHub actions support from GitTools. They have since rolled out their own official support at https://github.com/marketplace/actions/gittools. You should use that one instead.

I have delisted my action as it should no longer be used.
